name: "Gereksiz"
markdown: kmarkdown
highlighter: pygments
permalink: :title
exclude: [README.md, LICENSE, Makefile]
url: http://dclcs.github.io

# Information for the Atom feed
gereksiz:
   author: "John Doe"
   email: "john.doe@mail.sexy"