title: dcl
description: Learning
author: dcl
post_author: dcl
logo: /img/avatar.png
github: https://github.com/dclcs
about: blog
mail: "2351741841@qq.com"

url: "https://dclcs.github.io"

allowsearch: false

share:
  twitter_username: none


enableTags: true
tagarray: []

excerpt_separator: "<!--more-->"
paginate: 30
per_page: 30
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "dcl"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "dcl"
      permalink: "/article/:title.html"
